name: Build and deploy Python project to Azure Function App - gatewayfunction

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for Azure login via OIDC
      contents: read    # Required for GitHub checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt --target="./.python_packages/lib/site-packages"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_40B0D96216D0457F99D0B6F05DB2DAE1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AC587909CF7A4B55A7C5BAE0D94DD105 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3C866936527B42C684CCE58238E93FEC }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'gatewayfunction'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
